### ISSUE TITLE
Just opensource a part of code

### ISSUE THREAD

**Issue by hyx100e** [olivettigroup/table_extractor#2]
Hi, 
I read your paper https://pubs.acs.org/doi/abs/10.1021/acscentsci.9b00193
And it is very similar to our work. That is an exciting job, But I noticed that you just open sourced the code about the table extraction part.
That is very important about text extraction and I want to know how did you extract information from table as shown in the zeolite_data/xlsx or csv. 
Can you open source the entire code if you like?
This is very important to me and will greatly advance our work
Thanks

**Comment by zjensen262** [comment]
Hello, unfortunately, I don't think we can release that part of the code at this time, but I will follow up to make sure. The procedure for that part of the code is generally described in the Data Extraction and Data Engineering sections of the paper.
